// Exports typed ABIs (as const) from contracts/out into app/src/abi and scripts/src/abi.
// Run after `forge build`:  pnpm abis
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const contracts = [
  "AuctionHouse",
  "TermRegistry",
  "RepoLocker",
  "RepoNote",
  "MarginEngine",
  "Liquidator",
  "NoteMarket",
  "MarketClock",
  "OracleAdapter",
  "FeeCollector",
  "ProjectTokenHooks",
  "ComplianceRegistry",
  "OvernightTimelock",
];
const erc20 = [
  { type: "function", name: "balanceOf", stateMutability: "view", inputs: [{ name: "a", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "allowance", stateMutability: "view", inputs: [{ name: "o", type: "address" }, { name: "s", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "approve", stateMutability: "nonpayable", inputs: [{ name: "s", type: "address" }, { name: "v", type: "uint256" }], outputs: [{ type: "bool" }] },
  { type: "function", name: "decimals", stateMutability: "view", inputs: [], outputs: [{ type: "uint8" }] },
  { type: "function", name: "symbol", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
];

for (const outDir of ["app/src/abi", "scripts/src/abi"]) {
  const dir = join(root, outDir);
  mkdirSync(dir, { recursive: true });
  const index = [];
  for (const name of contracts) {
    const artifact = JSON.parse(readFileSync(join(root, "contracts/out", `${name}.sol`, `${name}.json`), "utf8"));
    writeFileSync(join(dir, `${name}.ts`), `// generated by scripts/export-abis.mjs - do not edit\nexport const ${name}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`);
    index.push(`export { ${name}Abi } from "./${name}";`);
  }
  writeFileSync(join(dir, "ERC20.ts"), `export const ERC20Abi = ${JSON.stringify(erc20, null, 2)} as const;\n`);
  index.push(`export { ERC20Abi } from "./ERC20";`);
  writeFileSync(join(dir, "index.ts"), index.join("\n") + "\n");
  console.log(`wrote ${contracts.length + 1} ABIs to ${outDir}`);
}
